const readLine=require('readline-sync');
let words=[]

let word=readLine.question("noun")
words.push(word)
let word1=readLine.question("adjective")
words.push(word1)
let word2=readLine.question("adjective")
words.push(word2)
let word3=readLine.question("noun")
words.push(word3)
let word4=readLine.question("noun")
words.push(word4)
let word5=readLine.question("noun")
words.push(word5)
let word6=readLine.question("noun")
words.push(word6)
let word7=readLine.question("adjective")
words.push(word7)
let word8=readLine.question("noun")
words.push(word8)
let word9=readLine.question("noun")
words.push(word9)
let word10=readLine.question("noun")
words.push(word10)
let word11=readLine.question("adjective")
words.push(word12)
let word12=readLine.question("adjective")
words.push(word13)
let word13=readLine.question("adjective")
words.push(word14)
let word14=readLine.question("noun")
words.push(word15)
let word15=readLine.question("noun")
words.push(word16)
let word16=readLine.question("noun")
words.push(word17)
let word17=readLine.question("noun")
words.push(word18)
let word18=readLine.question("adjective")
words.push(word19)
let word19=readLine.question("noun")
words.push(word20)
let word20=readLine.question("verb")
words.push(word21)
let word21=readLine.question("noun")
words.push(word22)
let word23=readLine.question("adjective")
words.push(word23)
let word24=readLine.question("noun")
words.push(word24)

